env:
    browser: true
    es2021: true
extends:
    - 'eslint:recommended'
    - 'plugin:react/recommended'
    - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
rules:
    react/react-in-jsx-scope: off
    arrow-body-style:
        - warn
        - as-needed
    no-constant-condition:
        - warn
        - checkLoops: false
    prefer-const: warn
    '@typescript-eslint/explicit-function-return-type':
        - off
        - allowExpressions: true
    '@typescript-eslint/explicit-module-boundary-types': off
    '@typescript-eslint/no-inferrable-types': warn
